// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.1
// source: msg/cmsg/cmsg.proto

package cmsg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RespLogin_Error int32

const (
	RespLogin_Invalid  RespLogin_Error = 0
	RespLogin_RPCError RespLogin_Error = 1
)

// Enum value maps for RespLogin_Error.
var (
	RespLogin_Error_name = map[int32]string{
		0: "Invalid",
		1: "RPCError",
	}
	RespLogin_Error_value = map[string]int32{
		"Invalid":  0,
		"RPCError": 1,
	}
)

func (x RespLogin_Error) Enum() *RespLogin_Error {
	p := new(RespLogin_Error)
	*p = x
	return p
}

func (x RespLogin_Error) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RespLogin_Error) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_cmsg_cmsg_proto_enumTypes[0].Descriptor()
}

func (RespLogin_Error) Type() protoreflect.EnumType {
	return &file_msg_cmsg_cmsg_proto_enumTypes[0]
}

func (x RespLogin_Error) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RespLogin_Error.Descriptor instead.
func (RespLogin_Error) EnumDescriptor() ([]byte, []int) {
	return file_msg_cmsg_cmsg_proto_rawDescGZIP(), []int{1, 0}
}

type RespMatch_Error int32

const (
	RespMatch_Invalid        RespMatch_Error = 0
	RespMatch_UserNotExisted RespMatch_Error = 1
	RespMatch_AlreadyInGame  RespMatch_Error = 2
)

// Enum value maps for RespMatch_Error.
var (
	RespMatch_Error_name = map[int32]string{
		0: "Invalid",
		1: "UserNotExisted",
		2: "AlreadyInGame",
	}
	RespMatch_Error_value = map[string]int32{
		"Invalid":        0,
		"UserNotExisted": 1,
		"AlreadyInGame":  2,
	}
)

func (x RespMatch_Error) Enum() *RespMatch_Error {
	p := new(RespMatch_Error)
	*p = x
	return p
}

func (x RespMatch_Error) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RespMatch_Error) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_cmsg_cmsg_proto_enumTypes[1].Descriptor()
}

func (RespMatch_Error) Type() protoreflect.EnumType {
	return &file_msg_cmsg_cmsg_proto_enumTypes[1]
}

func (x RespMatch_Error) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RespMatch_Error.Descriptor instead.
func (RespMatch_Error) EnumDescriptor() ([]byte, []int) {
	return file_msg_cmsg_cmsg_proto_rawDescGZIP(), []int{3, 0}
}

type RespGameLogin_Error int32

const (
	RespGameLogin_Invalid      RespGameLogin_Error = 0
	RespGameLogin_GameNotExist RespGameLogin_Error = 1
)

// Enum value maps for RespGameLogin_Error.
var (
	RespGameLogin_Error_name = map[int32]string{
		0: "Invalid",
		1: "GameNotExist",
	}
	RespGameLogin_Error_value = map[string]int32{
		"Invalid":      0,
		"GameNotExist": 1,
	}
)

func (x RespGameLogin_Error) Enum() *RespGameLogin_Error {
	p := new(RespGameLogin_Error)
	*p = x
	return p
}

func (x RespGameLogin_Error) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RespGameLogin_Error) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_cmsg_cmsg_proto_enumTypes[2].Descriptor()
}

func (RespGameLogin_Error) Type() protoreflect.EnumType {
	return &file_msg_cmsg_cmsg_proto_enumTypes[2]
}

func (x RespGameLogin_Error) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RespGameLogin_Error.Descriptor instead.
func (RespGameLogin_Error) EnumDescriptor() ([]byte, []int) {
	return file_msg_cmsg_cmsg_proto_rawDescGZIP(), []int{6, 0}
}

type RespClientReady_Error int32

const (
	RespClientReady_Invalid      RespClientReady_Error = 0
	RespClientReady_GameNotExist RespClientReady_Error = 1
)

// Enum value maps for RespClientReady_Error.
var (
	RespClientReady_Error_name = map[int32]string{
		0: "Invalid",
		1: "GameNotExist",
	}
	RespClientReady_Error_value = map[string]int32{
		"Invalid":      0,
		"GameNotExist": 1,
	}
)

func (x RespClientReady_Error) Enum() *RespClientReady_Error {
	p := new(RespClientReady_Error)
	*p = x
	return p
}

func (x RespClientReady_Error) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RespClientReady_Error) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_cmsg_cmsg_proto_enumTypes[3].Descriptor()
}

func (RespClientReady_Error) Type() protoreflect.EnumType {
	return &file_msg_cmsg_cmsg_proto_enumTypes[3]
}

func (x RespClientReady_Error) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RespClientReady_Error.Descriptor instead.
func (RespClientReady_Error) EnumDescriptor() ([]byte, []int) {
	return file_msg_cmsg_cmsg_proto_rawDescGZIP(), []int{8, 0}
}

type Input_Type int32

const (
	Input_None  Input_Type = 0
	Input_Move  Input_Type = 1
	Input_Shoot Input_Type = 2
)

// Enum value maps for Input_Type.
var (
	Input_Type_name = map[int32]string{
		0: "None",
		1: "Move",
		2: "Shoot",
	}
	Input_Type_value = map[string]int32{
		"None":  0,
		"Move":  1,
		"Shoot": 2,
	}
)

func (x Input_Type) Enum() *Input_Type {
	p := new(Input_Type)
	*p = x
	return p
}

func (x Input_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Input_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_cmsg_cmsg_proto_enumTypes[4].Descriptor()
}

func (Input_Type) Type() protoreflect.EnumType {
	return &file_msg_cmsg_cmsg_proto_enumTypes[4]
}

func (x Input_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Input_Type.Descriptor instead.
func (Input_Type) EnumDescriptor() ([]byte, []int) {
	return file_msg_cmsg_cmsg_proto_rawDescGZIP(), []int{12, 0}
}

type SNoticeKickOut_Reason int32

const (
	SNoticeKickOut_Invalid SNoticeKickOut_Reason = 0
	SNoticeKickOut_Relogin SNoticeKickOut_Reason = 1 //重复登录被T出
)

// Enum value maps for SNoticeKickOut_Reason.
var (
	SNoticeKickOut_Reason_name = map[int32]string{
		0: "Invalid",
		1: "Relogin",
	}
	SNoticeKickOut_Reason_value = map[string]int32{
		"Invalid": 0,
		"Relogin": 1,
	}
)

func (x SNoticeKickOut_Reason) Enum() *SNoticeKickOut_Reason {
	p := new(SNoticeKickOut_Reason)
	*p = x
	return p
}

func (x SNoticeKickOut_Reason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SNoticeKickOut_Reason) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_cmsg_cmsg_proto_enumTypes[5].Descriptor()
}

func (SNoticeKickOut_Reason) Type() protoreflect.EnumType {
	return &file_msg_cmsg_cmsg_proto_enumTypes[5]
}

func (x SNoticeKickOut_Reason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SNoticeKickOut_Reason.Descriptor instead.
func (SNoticeKickOut_Reason) EnumDescriptor() ([]byte, []int) {
	return file_msg_cmsg_cmsg_proto_rawDescGZIP(), []int{17, 0}
}

type ReqLogin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *ReqLogin) Reset() {
	*x = ReqLogin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_cmsg_cmsg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqLogin) ProtoMessage() {}

func (x *ReqLogin) ProtoReflect() protoreflect.Message {
	mi := &file_msg_cmsg_cmsg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqLogin.ProtoReflect.Descriptor instead.
func (*ReqLogin) Descriptor() ([]byte, []int) {
	return file_msg_cmsg_cmsg_proto_rawDescGZIP(), []int{0}
}

func (x *ReqLogin) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type RespLogin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err    RespLogin_Error `protobuf:"varint,1,opt,name=err,proto3,enum=RespLogin_Error" json:"err,omitempty"`
	UserID uint64          `protobuf:"varint,2,opt,name=userID,proto3" json:"userID,omitempty"`
	Token  string          `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *RespLogin) Reset() {
	*x = RespLogin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_cmsg_cmsg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespLogin) ProtoMessage() {}

func (x *RespLogin) ProtoReflect() protoreflect.Message {
	mi := &file_msg_cmsg_cmsg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespLogin.ProtoReflect.Descriptor instead.
func (*RespLogin) Descriptor() ([]byte, []int) {
	return file_msg_cmsg_cmsg_proto_rawDescGZIP(), []int{1}
}

func (x *RespLogin) GetErr() RespLogin_Error {
	if x != nil {
		return x.Err
	}
	return RespLogin_Invalid
}

func (x *RespLogin) GetUserID() uint64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *RespLogin) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ReqMatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nickname string `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
}

func (x *ReqMatch) Reset() {
	*x = ReqMatch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_cmsg_cmsg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqMatch) ProtoMessage() {}

func (x *ReqMatch) ProtoReflect() protoreflect.Message {
	mi := &file_msg_cmsg_cmsg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqMatch.ProtoReflect.Descriptor instead.
func (*ReqMatch) Descriptor() ([]byte, []int) {
	return file_msg_cmsg_cmsg_proto_rawDescGZIP(), []int{2}
}

func (x *ReqMatch) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type RespMatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err      RespMatch_Error `protobuf:"varint,1,opt,name=err,proto3,enum=RespMatch_Error" json:"err,omitempty"`
	Nickname string          `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
}

func (x *RespMatch) Reset() {
	*x = RespMatch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_cmsg_cmsg_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespMatch) ProtoMessage() {}

func (x *RespMatch) ProtoReflect() protoreflect.Message {
	mi := &file_msg_cmsg_cmsg_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespMatch.ProtoReflect.Descriptor instead.
func (*RespMatch) Descriptor() ([]byte, []int) {
	return file_msg_cmsg_cmsg_proto_rawDescGZIP(), []int{3}
}

func (x *RespMatch) GetErr() RespMatch_Error {
	if x != nil {
		return x.Err
	}
	return RespMatch_Invalid
}

func (x *RespMatch) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type SNotifyGameReady struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameAddr string `protobuf:"bytes,1,opt,name=gameAddr,proto3" json:"gameAddr,omitempty"` //游戏服务器连接地址
}

func (x *SNotifyGameReady) Reset() {
	*x = SNotifyGameReady{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_cmsg_cmsg_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SNotifyGameReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SNotifyGameReady) ProtoMessage() {}

func (x *SNotifyGameReady) ProtoReflect() protoreflect.Message {
	mi := &file_msg_cmsg_cmsg_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SNotifyGameReady.ProtoReflect.Descriptor instead.
func (*SNotifyGameReady) Descriptor() ([]byte, []int) {
	return file_msg_cmsg_cmsg_proto_rawDescGZIP(), []int{4}
}

func (x *SNotifyGameReady) GetGameAddr() string {
	if x != nil {
		return x.GameAddr
	}
	return ""
}

type ReqGameLogin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   uint64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Nickname string `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
}

func (x *ReqGameLogin) Reset() {
	*x = ReqGameLogin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_cmsg_cmsg_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqGameLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGameLogin) ProtoMessage() {}

func (x *ReqGameLogin) ProtoReflect() protoreflect.Message {
	mi := &file_msg_cmsg_cmsg_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGameLogin.ProtoReflect.Descriptor instead.
func (*ReqGameLogin) Descriptor() ([]byte, []int) {
	return file_msg_cmsg_cmsg_proto_rawDescGZIP(), []int{5}
}

func (x *ReqGameLogin) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ReqGameLogin) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type RespGameLogin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err RespGameLogin_Error `protobuf:"varint,1,opt,name=err,proto3,enum=RespGameLogin_Error" json:"err,omitempty"`
}

func (x *RespGameLogin) Reset() {
	*x = RespGameLogin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_cmsg_cmsg_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespGameLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespGameLogin) ProtoMessage() {}

func (x *RespGameLogin) ProtoReflect() protoreflect.Message {
	mi := &file_msg_cmsg_cmsg_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespGameLogin.ProtoReflect.Descriptor instead.
func (*RespGameLogin) Descriptor() ([]byte, []int) {
	return file_msg_cmsg_cmsg_proto_rawDescGZIP(), []int{6}
}

func (x *RespGameLogin) GetErr() RespGameLogin_Error {
	if x != nil {
		return x.Err
	}
	return RespGameLogin_Invalid
}

type ReqClientReady struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqClientReady) Reset() {
	*x = ReqClientReady{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_cmsg_cmsg_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqClientReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqClientReady) ProtoMessage() {}

func (x *ReqClientReady) ProtoReflect() protoreflect.Message {
	mi := &file_msg_cmsg_cmsg_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqClientReady.ProtoReflect.Descriptor instead.
func (*ReqClientReady) Descriptor() ([]byte, []int) {
	return file_msg_cmsg_cmsg_proto_rawDescGZIP(), []int{7}
}

type RespClientReady struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err RespClientReady_Error `protobuf:"varint,1,opt,name=err,proto3,enum=RespClientReady_Error" json:"err,omitempty"`
}

func (x *RespClientReady) Reset() {
	*x = RespClientReady{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_cmsg_cmsg_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespClientReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespClientReady) ProtoMessage() {}

func (x *RespClientReady) ProtoReflect() protoreflect.Message {
	mi := &file_msg_cmsg_cmsg_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespClientReady.ProtoReflect.Descriptor instead.
func (*RespClientReady) Descriptor() ([]byte, []int) {
	return file_msg_cmsg_cmsg_proto_rawDescGZIP(), []int{8}
}

func (x *RespClientReady) GetErr() RespClientReady_Error {
	if x != nil {
		return x.Err
	}
	return RespClientReady_Invalid
}

type SNotifyGameStart struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RandSeed int64   `protobuf:"varint,1,opt,name=randSeed,proto3" json:"randSeed,omitempty"`
	Seats    []*Seat `protobuf:"bytes,2,rep,name=seats,proto3" json:"seats,omitempty"`
}

func (x *SNotifyGameStart) Reset() {
	*x = SNotifyGameStart{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_cmsg_cmsg_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SNotifyGameStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SNotifyGameStart) ProtoMessage() {}

func (x *SNotifyGameStart) ProtoReflect() protoreflect.Message {
	mi := &file_msg_cmsg_cmsg_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SNotifyGameStart.ProtoReflect.Descriptor instead.
func (*SNotifyGameStart) Descriptor() ([]byte, []int) {
	return file_msg_cmsg_cmsg_proto_rawDescGZIP(), []int{9}
}

func (x *SNotifyGameStart) GetRandSeed() int64 {
	if x != nil {
		return x.RandSeed
	}
	return 0
}

func (x *SNotifyGameStart) GetSeats() []*Seat {
	if x != nil {
		return x.Seats
	}
	return nil
}

type Seat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SeatId   int32  `protobuf:"varint,1,opt,name=seatId,proto3" json:"seatId,omitempty"`
	UserId   uint64 `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Nickname string `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
}

func (x *Seat) Reset() {
	*x = Seat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_cmsg_cmsg_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Seat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Seat) ProtoMessage() {}

func (x *Seat) ProtoReflect() protoreflect.Message {
	mi := &file_msg_cmsg_cmsg_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Seat.ProtoReflect.Descriptor instead.
func (*Seat) Descriptor() ([]byte, []int) {
	return file_msg_cmsg_cmsg_proto_rawDescGZIP(), []int{10}
}

func (x *Seat) GetSeatId() int32 {
	if x != nil {
		return x.SeatId
	}
	return 0
}

func (x *Seat) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Seat) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type ReqGameInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Input *Input `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
}

func (x *ReqGameInput) Reset() {
	*x = ReqGameInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_cmsg_cmsg_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqGameInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGameInput) ProtoMessage() {}

func (x *ReqGameInput) ProtoReflect() protoreflect.Message {
	mi := &file_msg_cmsg_cmsg_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGameInput.ProtoReflect.Descriptor instead.
func (*ReqGameInput) Descriptor() ([]byte, []int) {
	return file_msg_cmsg_cmsg_proto_rawDescGZIP(), []int{11}
}

func (x *ReqGameInput) GetInput() *Input {
	if x != nil {
		return x.Input
	}
	return nil
}

type Input struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type           Input_Type `protobuf:"varint,1,opt,name=type,proto3,enum=Input_Type" json:"type,omitempty"`
	PressTime      float32    `protobuf:"fixed32,2,opt,name=pressTime,proto3" json:"pressTime,omitempty"`
	TargetRotation float32    `protobuf:"fixed32,3,opt,name=targetRotation,proto3" json:"targetRotation,omitempty"`
}

func (x *Input) Reset() {
	*x = Input{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_cmsg_cmsg_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Input) ProtoMessage() {}

func (x *Input) ProtoReflect() protoreflect.Message {
	mi := &file_msg_cmsg_cmsg_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Input.ProtoReflect.Descriptor instead.
func (*Input) Descriptor() ([]byte, []int) {
	return file_msg_cmsg_cmsg_proto_rawDescGZIP(), []int{12}
}

func (x *Input) GetType() Input_Type {
	if x != nil {
		return x.Type
	}
	return Input_None
}

func (x *Input) GetPressTime() float32 {
	if x != nil {
		return x.PressTime
	}
	return 0
}

func (x *Input) GetTargetRotation() float32 {
	if x != nil {
		return x.TargetRotation
	}
	return 0
}

type SSyncFrame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Frame  uint32       `protobuf:"varint,1,opt,name=frame,proto3" json:"frame,omitempty"` //帧号
	Inputs []*SeatInput `protobuf:"bytes,2,rep,name=inputs,proto3" json:"inputs,omitempty"`
	Debug  string       `protobuf:"bytes,3,opt,name=debug,proto3" json:"debug,omitempty"` //显示信息(debug用）
}

func (x *SSyncFrame) Reset() {
	*x = SSyncFrame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_cmsg_cmsg_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SSyncFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSyncFrame) ProtoMessage() {}

func (x *SSyncFrame) ProtoReflect() protoreflect.Message {
	mi := &file_msg_cmsg_cmsg_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSyncFrame.ProtoReflect.Descriptor instead.
func (*SSyncFrame) Descriptor() ([]byte, []int) {
	return file_msg_cmsg_cmsg_proto_rawDescGZIP(), []int{13}
}

func (x *SSyncFrame) GetFrame() uint32 {
	if x != nil {
		return x.Frame
	}
	return 0
}

func (x *SSyncFrame) GetInputs() []*SeatInput {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *SSyncFrame) GetDebug() string {
	if x != nil {
		return x.Debug
	}
	return ""
}

type SeatInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seat  int32  `protobuf:"varint,1,opt,name=seat,proto3" json:"seat,omitempty"`
	Input *Input `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
}

func (x *SeatInput) Reset() {
	*x = SeatInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_cmsg_cmsg_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SeatInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeatInput) ProtoMessage() {}

func (x *SeatInput) ProtoReflect() protoreflect.Message {
	mi := &file_msg_cmsg_cmsg_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeatInput.ProtoReflect.Descriptor instead.
func (*SeatInput) Descriptor() ([]byte, []int) {
	return file_msg_cmsg_cmsg_proto_rawDescGZIP(), []int{14}
}

func (x *SeatInput) GetSeat() int32 {
	if x != nil {
		return x.Seat
	}
	return 0
}

func (x *SeatInput) GetInput() *Input {
	if x != nil {
		return x.Input
	}
	return nil
}

type ReqGameOver struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqGameOver) Reset() {
	*x = ReqGameOver{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_cmsg_cmsg_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqGameOver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGameOver) ProtoMessage() {}

func (x *ReqGameOver) ProtoReflect() protoreflect.Message {
	mi := &file_msg_cmsg_cmsg_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGameOver.ProtoReflect.Descriptor instead.
func (*ReqGameOver) Descriptor() ([]byte, []int) {
	return file_msg_cmsg_cmsg_proto_rawDescGZIP(), []int{15}
}

type SNotifyGameOver struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OverReason int32 `protobuf:"varint,1,opt,name=overReason,proto3" json:"overReason,omitempty"`
}

func (x *SNotifyGameOver) Reset() {
	*x = SNotifyGameOver{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_cmsg_cmsg_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SNotifyGameOver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SNotifyGameOver) ProtoMessage() {}

func (x *SNotifyGameOver) ProtoReflect() protoreflect.Message {
	mi := &file_msg_cmsg_cmsg_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SNotifyGameOver.ProtoReflect.Descriptor instead.
func (*SNotifyGameOver) Descriptor() ([]byte, []int) {
	return file_msg_cmsg_cmsg_proto_rawDescGZIP(), []int{16}
}

func (x *SNotifyGameOver) GetOverReason() int32 {
	if x != nil {
		return x.OverReason
	}
	return 0
}

// 通知被T出
type SNoticeKickOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reason SNoticeKickOut_Reason `protobuf:"varint,1,opt,name=reason,proto3,enum=SNoticeKickOut_Reason" json:"reason,omitempty"`
}

func (x *SNoticeKickOut) Reset() {
	*x = SNoticeKickOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_cmsg_cmsg_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SNoticeKickOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SNoticeKickOut) ProtoMessage() {}

func (x *SNoticeKickOut) ProtoReflect() protoreflect.Message {
	mi := &file_msg_cmsg_cmsg_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SNoticeKickOut.ProtoReflect.Descriptor instead.
func (*SNoticeKickOut) Descriptor() ([]byte, []int) {
	return file_msg_cmsg_cmsg_proto_rawDescGZIP(), []int{17}
}

func (x *SNoticeKickOut) GetReason() SNoticeKickOut_Reason {
	if x != nil {
		return x.Reason
	}
	return SNoticeKickOut_Invalid
}

var File_msg_cmsg_cmsg_proto protoreflect.FileDescriptor

var file_msg_cmsg_cmsg_proto_rawDesc = []byte{
	0x0a, 0x13, 0x6d, 0x73, 0x67, 0x2f, 0x63, 0x6d, 0x73, 0x67, 0x2f, 0x63, 0x6d, 0x73, 0x67, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x20, 0x0a, 0x08, 0x52, 0x65, 0x71, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x81, 0x01, 0x0a, 0x09, 0x52, 0x65, 0x73, 0x70,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x22, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x10, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x2e, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x52, 0x03, 0x65, 0x72, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x44, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x22, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x12, 0x0b, 0x0a, 0x07, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x10, 0x00, 0x12, 0x0c, 0x0a,
	0x08, 0x52, 0x50, 0x43, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x01, 0x22, 0x26, 0x0a, 0x08, 0x52,
	0x65, 0x71, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e,
	0x61, 0x6d, 0x65, 0x22, 0x88, 0x01, 0x0a, 0x09, 0x52, 0x65, 0x73, 0x70, 0x4d, 0x61, 0x74, 0x63,
	0x68, 0x12, 0x22, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x52, 0x03, 0x65, 0x72, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x3b, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x6e,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x55, 0x73, 0x65, 0x72, 0x4e,
	0x6f, 0x74, 0x45, 0x78, 0x69, 0x73, 0x74, 0x65, 0x64, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x41,
	0x6c, 0x72, 0x65, 0x61, 0x64, 0x79, 0x49, 0x6e, 0x47, 0x61, 0x6d, 0x65, 0x10, 0x02, 0x22, 0x2e,
	0x0a, 0x10, 0x53, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x61,
	0x64, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x41, 0x64, 0x64, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x41, 0x64, 0x64, 0x72, 0x22, 0x42,
	0x0a, 0x0c, 0x52, 0x65, 0x71, 0x47, 0x61, 0x6d, 0x65, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x16,
	0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0x5f, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x70, 0x47, 0x61, 0x6d, 0x65, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x12, 0x26, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x14, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x47, 0x61, 0x6d, 0x65, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x03, 0x65, 0x72, 0x72, 0x22, 0x26, 0x0a, 0x05, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x10,
	0x00, 0x12, 0x10, 0x0a, 0x0c, 0x47, 0x61, 0x6d, 0x65, 0x4e, 0x6f, 0x74, 0x45, 0x78, 0x69, 0x73,
	0x74, 0x10, 0x01, 0x22, 0x10, 0x0a, 0x0e, 0x52, 0x65, 0x71, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x61, 0x64, 0x79, 0x22, 0x63, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x70, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x61, 0x64, 0x79, 0x12, 0x28, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x61, 0x64, 0x79, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x03, 0x65,
	0x72, 0x72, 0x22, 0x26, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x0b, 0x0a, 0x07, 0x49,
	0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x47, 0x61, 0x6d, 0x65,
	0x4e, 0x6f, 0x74, 0x45, 0x78, 0x69, 0x73, 0x74, 0x10, 0x01, 0x22, 0x4b, 0x0a, 0x10, 0x53, 0x4e,
	0x6f, 0x74, 0x69, 0x66, 0x79, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x72, 0x61, 0x6e, 0x64, 0x53, 0x65, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x72, 0x61, 0x6e, 0x64, 0x53, 0x65, 0x65, 0x64, 0x12, 0x1b, 0x0a, 0x05, 0x73, 0x65,
	0x61, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x53, 0x65, 0x61, 0x74,
	0x52, 0x05, 0x73, 0x65, 0x61, 0x74, 0x73, 0x22, 0x52, 0x0a, 0x04, 0x53, 0x65, 0x61, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x65, 0x61, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x73, 0x65, 0x61, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x2c, 0x0a, 0x0c, 0x52,
	0x65, 0x71, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x1c, 0x0a, 0x05, 0x69,
	0x6e, 0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x49, 0x6e, 0x70,
	0x75, 0x74, 0x52, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x22, 0x95, 0x01, 0x0a, 0x05, 0x49, 0x6e,
	0x70, 0x75, 0x74, 0x12, 0x1f, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x0b, 0x2e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x65, 0x73, 0x73, 0x54, 0x69, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x70, 0x72, 0x65, 0x73, 0x73, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x52, 0x6f, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0e, 0x74, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x52, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x25, 0x0a, 0x04, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04,
	0x4d, 0x6f, 0x76, 0x65, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x53, 0x68, 0x6f, 0x6f, 0x74, 0x10,
	0x02, 0x22, 0x5c, 0x0a, 0x0a, 0x53, 0x53, 0x79, 0x6e, 0x63, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05,
	0x66, 0x72, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x06, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x53, 0x65, 0x61, 0x74, 0x49, 0x6e, 0x70, 0x75,
	0x74, 0x52, 0x06, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x65, 0x62,
	0x75, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x64, 0x65, 0x62, 0x75, 0x67, 0x22,
	0x3d, 0x0a, 0x09, 0x53, 0x65, 0x61, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x73, 0x65, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x65, 0x61, 0x74,
	0x12, 0x1c, 0x0a, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x06, 0x2e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x52, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x22, 0x0d,
	0x0a, 0x0b, 0x52, 0x65, 0x71, 0x47, 0x61, 0x6d, 0x65, 0x4f, 0x76, 0x65, 0x72, 0x22, 0x31, 0x0a,
	0x0f, 0x53, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x47, 0x61, 0x6d, 0x65, 0x4f, 0x76, 0x65, 0x72,
	0x12, 0x1e, 0x0a, 0x0a, 0x6f, 0x76, 0x65, 0x72, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x6f, 0x76, 0x65, 0x72, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e,
	0x22, 0x64, 0x0a, 0x0e, 0x53, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x4b, 0x69, 0x63, 0x6b, 0x4f,
	0x75, 0x74, 0x12, 0x2e, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x16, 0x2e, 0x53, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x4b, 0x69, 0x63, 0x6b,
	0x4f, 0x75, 0x74, 0x2e, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73,
	0x6f, 0x6e, 0x22, 0x22, 0x0a, 0x06, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x0b, 0x0a, 0x07,
	0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x65, 0x6c,
	0x6f, 0x67, 0x69, 0x6e, 0x10, 0x01, 0x42, 0x0a, 0x5a, 0x08, 0x6d, 0x73, 0x67, 0x2f, 0x63, 0x6d,
	0x73, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_msg_cmsg_cmsg_proto_rawDescOnce sync.Once
	file_msg_cmsg_cmsg_proto_rawDescData = file_msg_cmsg_cmsg_proto_rawDesc
)

func file_msg_cmsg_cmsg_proto_rawDescGZIP() []byte {
	file_msg_cmsg_cmsg_proto_rawDescOnce.Do(func() {
		file_msg_cmsg_cmsg_proto_rawDescData = protoimpl.X.CompressGZIP(file_msg_cmsg_cmsg_proto_rawDescData)
	})
	return file_msg_cmsg_cmsg_proto_rawDescData
}

var file_msg_cmsg_cmsg_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_msg_cmsg_cmsg_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_msg_cmsg_cmsg_proto_goTypes = []interface{}{
	(RespLogin_Error)(0),       // 0: RespLogin.Error
	(RespMatch_Error)(0),       // 1: RespMatch.Error
	(RespGameLogin_Error)(0),   // 2: RespGameLogin.Error
	(RespClientReady_Error)(0), // 3: RespClientReady.Error
	(Input_Type)(0),            // 4: Input.Type
	(SNoticeKickOut_Reason)(0), // 5: SNoticeKickOut.Reason
	(*ReqLogin)(nil),           // 6: ReqLogin
	(*RespLogin)(nil),          // 7: RespLogin
	(*ReqMatch)(nil),           // 8: ReqMatch
	(*RespMatch)(nil),          // 9: RespMatch
	(*SNotifyGameReady)(nil),   // 10: SNotifyGameReady
	(*ReqGameLogin)(nil),       // 11: ReqGameLogin
	(*RespGameLogin)(nil),      // 12: RespGameLogin
	(*ReqClientReady)(nil),     // 13: ReqClientReady
	(*RespClientReady)(nil),    // 14: RespClientReady
	(*SNotifyGameStart)(nil),   // 15: SNotifyGameStart
	(*Seat)(nil),               // 16: Seat
	(*ReqGameInput)(nil),       // 17: ReqGameInput
	(*Input)(nil),              // 18: Input
	(*SSyncFrame)(nil),         // 19: SSyncFrame
	(*SeatInput)(nil),          // 20: SeatInput
	(*ReqGameOver)(nil),        // 21: ReqGameOver
	(*SNotifyGameOver)(nil),    // 22: SNotifyGameOver
	(*SNoticeKickOut)(nil),     // 23: SNoticeKickOut
}
var file_msg_cmsg_cmsg_proto_depIdxs = []int32{
	0,  // 0: RespLogin.err:type_name -> RespLogin.Error
	1,  // 1: RespMatch.err:type_name -> RespMatch.Error
	2,  // 2: RespGameLogin.err:type_name -> RespGameLogin.Error
	3,  // 3: RespClientReady.err:type_name -> RespClientReady.Error
	16, // 4: SNotifyGameStart.seats:type_name -> Seat
	18, // 5: ReqGameInput.input:type_name -> Input
	4,  // 6: Input.type:type_name -> Input.Type
	20, // 7: SSyncFrame.inputs:type_name -> SeatInput
	18, // 8: SeatInput.input:type_name -> Input
	5,  // 9: SNoticeKickOut.reason:type_name -> SNoticeKickOut.Reason
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_msg_cmsg_cmsg_proto_init() }
func file_msg_cmsg_cmsg_proto_init() {
	if File_msg_cmsg_cmsg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_msg_cmsg_cmsg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqLogin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_cmsg_cmsg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespLogin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_cmsg_cmsg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqMatch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_cmsg_cmsg_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespMatch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_cmsg_cmsg_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SNotifyGameReady); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_cmsg_cmsg_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqGameLogin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_cmsg_cmsg_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespGameLogin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_cmsg_cmsg_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqClientReady); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_cmsg_cmsg_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespClientReady); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_cmsg_cmsg_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SNotifyGameStart); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_cmsg_cmsg_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Seat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_cmsg_cmsg_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqGameInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_cmsg_cmsg_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Input); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_cmsg_cmsg_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SSyncFrame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_cmsg_cmsg_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SeatInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_cmsg_cmsg_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqGameOver); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_cmsg_cmsg_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SNotifyGameOver); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_cmsg_cmsg_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SNoticeKickOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msg_cmsg_cmsg_proto_rawDesc,
			NumEnums:      6,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msg_cmsg_cmsg_proto_goTypes,
		DependencyIndexes: file_msg_cmsg_cmsg_proto_depIdxs,
		EnumInfos:         file_msg_cmsg_cmsg_proto_enumTypes,
		MessageInfos:      file_msg_cmsg_cmsg_proto_msgTypes,
	}.Build()
	File_msg_cmsg_cmsg_proto = out.File
	file_msg_cmsg_cmsg_proto_rawDesc = nil
	file_msg_cmsg_cmsg_proto_goTypes = nil
	file_msg_cmsg_cmsg_proto_depIdxs = nil
}
